name: Tests
on: [push]
jobs:
  tests:
    name: Tests
    runs-on: windows-2022
    steps:
      - name: Execute tests
      - uses: actions/checkout@v3
      - run: .\duplicate_files.ps1 -SrcDir .\tests\src -DstDir .\tests\dst -LogFile .\tests\log.csv
      - run: ls
      - run: Get-Content .\tests\log.csv
