tests:
  name: Tests
  runs-on: windows-2022
  steps:
    - name: Execute tests
      run: |
        ls
        .\duplicate_files.ps1 -SrcDir .\tests\src\ -DstDir .\tests\dst\ -LogFile .\tests/log.csv
      shell: powershell
