name: tests
on: [push]
jobs:
  tests:
    runs-on: windows-2022
    steps:
      - run: .\duplicate_files.ps1 -SrcDir .\tests\src\ -DstDir .\tests\dst\ -LogFile .\tests/log.csv
      - run: ls .\tests\dst
      - run: cat .\tests\log.csv
