name: Tests
on: [pull_request]
jobs:
  tests_wser2022:
    name: Tests on Windows Server 2022
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - run: .\duplicate_files.ps1 -SrcDir .\tests\src -DstDir .\tests\dst -LogFile .\tests\log.csv
      - run: .\tests\tests.ps1
  tests_wser2019:
    name: Tests on Windows Server 2019
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - run: .\duplicate_files.ps1 -SrcDir .\tests\src -DstDir .\tests\dst -LogFile .\tests\log.csv
      - run: .\tests\tests.ps1
