name: Tests
on: [push]
jobs:
  tests:
    name: Tests
    runs-on: windows-2022
    steps:
      - name: Execute tests
        shell: pwsh
        run: |
          .\${{ github.action_path }}\duplicate_files.ps1 -SrcDir ${{ github.action_path }}\tests\src -DstDir ${{ github.action_path }}\tests\dst -LogFile ${{ github.action_path }}\tests\log.csv
